kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: iap
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000
        hostPort: 8000
        protocol: TCP
      - containerPort: 30001
        hostPort: 8001
        protocol: TCP
      - containerPort: 30002
        hostPort: 8002
        protocol: TCP
      - containerPort: 30003
        hostPort: 3000
        protocol: TCP
      - containerPort: 30004
        hostPort: 8003
        protocol: TCP
      - containerPort: 30005
        hostPort: 8004
        protocol: TCP
      - containerPort: 30100
        hostPort: 3100
        protocol: TCP
